export const GET_COMPANY_TABLE_DATA_REQUEST = "GET_COMPANY_TABLE_DATA_REQUEST";
export const GET_COMPANY_TABLE_DATA_SUCCESS = "GET_COMPANY_TABLE_DATA_SUCCESS";
export const GET_COMPANY_TABLE_DATA_FAILURE = "GET_COMPANY_TABLE_DATA_FAILURE";
export const GET_COMPANY_TABLE_DATA_RESET = "GET_COMPANY_TABLE_DATA_RESET";

export const GET_COMPANY_PROFILE_REQUEST = "GET_COMPANY_PROFILE_REQUEST";
export const GET_COMPANY_PROFILE_SUCCESS = "GET_COMPANY_PROFILE_SUCCESS";
export const GET_COMPANY_PROFILE_FAILURE = "GET_COMPANY_PROFILE_FAILURE";
export const GET_COMPANY_PROFILE_RESET = "GET_COMPANY_PROFILE_RESET";

export const ADD_COMPANY_TABLE_DATA_REQUEST = "ADD_COMPANY_TABLE_DATA_REQUEST";
export const ADD_COMPANY_TABLE_DATA_SUCCESS = "ADD_COMPANY_TABLE_DATA_SUCCESS";
export const ADD_COMPANY_TABLE_DATA_FAILURE = "ADD_COMPANY_TABLE_DATA_FAILURE";
export const ADD_COMPANY_TABLE_DATA_RESET = "ADD_COMPANY_TABLE_DATA_RESET";

export const EDIT_COMPANY_TABLE_DATA_REQUEST = "EDIT_COMPANY_TABLE_DATA_REQUEST";
export const EDIT_COMPANY_TABLE_DATA_SUCCESS = "EDIT_COMPANY_TABLE_DATA_SUCCESS";
export const EDIT_COMPANY_TABLE_DATA_FAILURE = "EDIT_COMPANY_TABLE_DATA_FAILURE";
export const EDIT_COMPANY_TABLE_DATA_RESET = "EDIT_COMPANY_TABLE_DATA_RESET";

export const DELETE_COMPANY_TABLE_DATA_REQUEST = "DELETE_COMPANY_TABLE_DATA_REQUEST";
export const DELETE_COMPANY_TABLE_DATA_SUCCESS = "DELETE_COMPANY_TABLE_DATA_SUCCESS";
export const DELETE_COMPANY_TABLE_DATA_FAILURE = "DELETE_COMPANY_TABLE_DATA_FAILURE";
export const DELETE_COMPANY_TABLE_DATA_RESET = "DELETE_COMPANY_TABLE_DATA_RESET";